version: 2

updates:
  # --- NPM
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      time: '07:00'
      timezone: Europe/Rome
    open-pull-requests-limit: 10
    labels:
      - dependencies
    versioning-strategy: increase-if-necessary
  
  # --- GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      time: '07:00'
      timezone: Europe/Rome
