# This workflow will do a clean install of node dependencies and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node CI

# --- Run pipeline only for "master" changes
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    # --- Ubuntu agent
    runs-on: ubuntu-latest

    # --- Execute the job with different versions of Node
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    # --- Job tasks
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
